{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gfa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GFA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GFA/GFA_{{ version }}.tar.gz
  sha256: 4d75b1effb0e31821b07386a900cf68e304c9925c3f2226c45ad2cae4450b7d1

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('GFA')"           # [not win]
    - "\"%R%\" -e \"library('GFA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GFA
  license: MIT
  summary: Factor analysis implementation for multiple data sources, i.e., for groups of variables. The whole data analysis pipeline is provided, including functions and recommendations for data normalization and model definition, as well as missing value prediction and model visualization. The model group factor analysis
    (GFA) is inferred with Gibbs sampling, and it has been presented originally by Virtanen et al. (2012), and extended in Klami et al. (2015) <DOI:10.1109/TNNLS.2014.2376974> and Bunte et al. (2016) <DOI:10.1093/bioinformatics/btw207>; for details, see the citation info.
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: GFA
# Type: Package
# Title: Group Factor Analysis
# Version: 1.0.3
# Date: 2017-08-04
# Authors@R: c(person("Eemeli", "Leppaaho", role = c("aut","cre"), email = "eemeli.leppaaho@gmail.com"), person("Seppo", "Virtanen", role = c("aut"), email = "s.virtanen@warwick.ac.uk"), person("Muhammad", "Ammad-ud-din", role = "ctb", email = "muhammad.ammad-ud-din@aalto.fi"), person("Suleiman A", "Khan", role = "ctb", email = "suleiman.khan@helsinki.fi"), person("Tommi", "Suvitaival", role = "ctb", email = "tsvv@steno.dk"), person("Inka", "Saarinen", role = "ctb", email = "inka.saarinen@aalto.fi"), person("Samuel", "Kaski", role = "ctb", email = "samuel.kaski@aalto.fi"))
# Author: Eemeli Leppaaho [aut, cre], Seppo Virtanen [aut], Muhammad Ammad-ud-din [ctb], Suleiman A Khan [ctb], Tommi Suvitaival [ctb], Inka Saarinen [ctb], Samuel Kaski [ctb]
# Maintainer: Eemeli Leppaaho <eemeli.leppaaho@gmail.com>
# Description: Factor analysis implementation for multiple data sources, i.e., for groups of variables. The whole data analysis pipeline is provided, including functions and recommendations for data normalization and model definition, as well as missing value prediction and model visualization. The model group factor analysis (GFA) is inferred with Gibbs sampling, and it has been presented originally by Virtanen et al. (2012), and extended in Klami et al. (2015) <DOI:10.1109/TNNLS.2014.2376974> and Bunte et al. (2016) <DOI:10.1093/bioinformatics/btw207>; for details, see the citation info.
# License: MIT + file LICENSE
# Encoding: latin1
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-08-04 07:12:25 UTC; eleppaah
# Repository: CRAN
# Date/Publication: 2017-08-04 08:53:59 UTC
