appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: u5P9er6KVgRl4W93AMvvNoy5lJbw8D28ZtYMNqe89DUiwqiokb2fv28kEd6FlRkHvdxENA2bwws05Hir5CvhAv+aCuHA6BAPFY5UCjlWR/dBFP6h3Md+SCK+neLUYhEYPhwBSMcy1V0+fkKvxg1F8OcSEhUBNl2qDjOvt7onAfQFWSLZdWuwwhfMQMHkCJXbrN22hMpPgwC7J4Q3L/hKzqx1k19sZFYjbMMmNDOsQkTm/3jx+kKv7+R5kOmVT/TaJ+3I9VWplp5BWhauCIaDSwfOSUavQx38mYax2J0D2Ppp4PiLBo19lwilaER4jaFWJrNud9SFmFwxV9P8FTCme1hNmHBzO1+/cHuMfyNFFDCtn5Aauu2OAAuM+DLmsVMO/wAtBZmOSzk6amKi3u2++XvUHnwZhXmTlCGlDq656l+yuodDdvTEUYkvaFQMXQl/SSBFZgZvenXxUyYGDYM1fG0kkulm1E9omkiyU9nAsBtrN2P+liIOnxrAV6a8ShLU2eixmxhe4/Leq9vETVvYUos5nrRp4uz6fONckFkIM65ICEAPeBmSdzs/lIdXebgrc7hKuV4bADlTD0JsCc7U+HwGQuo0Q6dwqcQmxErGj38Dpeu5JyEHsn9vLNHmDmDDWtVO+GJS3Ma4UPEirL8wxBR7LWfSokPJ8tEfvMR5Ad0=}
